[versions]
minecraft = "1.21.11"
quilt_mappings = "1.21.11+build.2"
fabric_loader = "0.18.4"

fabric_api = "0.141.3+1.21.11"

# Other mods
recursive_resources = "2.7.2+1.21.7"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
fabric_loader =  { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

recursive_resources = { module = "nl.enjarai:recursive-resources", version.ref = "recursive_resources" }

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.13.6" }
minotaur = { id = "com.modrinth.minotaur", version = "2.8.10" }
cursegradle = { id = "com.matthewprenger.cursegradle", version = "1.4.0" }
